import Image from "next/image";
import Link from "next/link";
import { ArrowDownRight, ArrowRight, BadgeCheck, Building2, Clock3, Cog, Droplets, Headphones, Leaf, MapPin, MessageCircle, Phone, ShieldCheck, Target, ThumbsUp, Trophy, UsersRound, Wrench } from "lucide-react";
import { BUSINESS_ADDRESS, publicBusinessFacts, WHATSAPP_NUMBER } from "./business-config";
import { MobileMenu } from "./mobile-menu";
import { EnquiryPopup } from "./enquiry-popup";
import { verifiedDevelopers } from "./verified-projects";
import { ScrollNav } from "./scroll-nav";
import { LeadForm } from "./lead-form";
import { getProductionUrl } from "./site-url";
import { CustomerReviews } from "./customer-reviews";
import { customerRating, customerRatingSource, customerReviews } from "./customer-reviews-data";
import { getIndexableSeoPages } from "./seo-pages";
import { buildHomePageSchema, buildLocalBusinessSchema } from "../lib/seo/page-schema";

const phone = publicBusinessFacts.phone;
const whatsapp = /^\d{10,15}$/.test(WHATSAPP_NUMBER.replace(/\D/g, "")) ? WHATSAPP_NUMBER.replace(/\D/g, "") : null;
const email = publicBusinessFacts.email;
const contactHref = phone ? `tel:${phone.replace(/[^+\d]/g, "")}` : "#contact";
const whatsappHref = whatsapp ? `https://wa.me/${whatsapp}?text=${encodeURIComponent("Hello Eshan Borewells, I would like to discuss a borewell site visit. My location is: ")}` : null;

const services = [
  { number: "01", title: "Borewell drilling", description: "Drilling planned around your site, access and property requirements.", image: "/large-drilling-rig.webp", alt: "Large borewell drilling rig working on open land near Bengaluru", imageTitle: "Borewell drilling for open plots and farms in Bengaluru" },
  { number: "02", title: "Water detection & survey", description: "A grounded assessment to help decide where and how to proceed.", image: "/survey-technician.webp", alt: "Technician reviewing a groundwater survey before borewell drilling", imageTitle: "Groundwater survey and water detection in Bengaluru" },
  { number: "03", title: "Casing & completion", description: "The supporting work needed to protect and complete a new borewell.", image: "/casing-installation.webp", alt: "Borewell casing installation during well completion", imageTitle: "Borewell casing and completion work" },
  { number: "04", title: "Flushing & redevelopment", description: "Care for suitable existing wells, assessed against their condition.", image: "/borewell-water-flow.webp", alt: "Water flowing from a borewell pipe after flushing", imageTitle: "Borewell flushing and redevelopment" },
];

const areaGroups = [
  { heading: "North & northwest", areas: ["Rajajinagar", "Yeshwanthpur", "Peenya", "Jalahalli", "Yelahanka", "Hebbal", "Sahakara Nagar", "Devanahalli", "Doddaballapur", "Nelamangala"] },
  { heading: "East & northeast", areas: ["Whitefield", "Marathahalli", "Mahadevapura", "KR Puram", "Hennur", "Horamavu", "Sarjapur Road", "Hoskote"] },
  { heading: "South & southeast", areas: ["Jayanagar", "JP Nagar", "Banashankari", "BTM Layout", "Electronic City", "Bommasandra", "Anekal", "Kanakapura Road"] },
  { heading: "West & beyond", areas: ["Vijayanagar", "Nagarbhavi", "Kengeri", "RR Nagar", "Mysore Road", "Ramanagara", "Chikkaballapur", "Hosur"] },
];
const indexableSeoPages = getIndexableSeoPages();

const whyCards = [
  { title: "Groundwater assessment", description: <>Survey findings can inform site planning, but groundwater conditions vary and no method can guarantee water.</>, image: "/survey-technician.webp", alt: "Technician using groundwater survey equipment before drilling", imageTitle: "Groundwater survey before borewell drilling", tag: "Survey-guided planning", Icon: Target },
  { title: "Drilling equipment options", description: <>Large, compact and robotic rigs may be considered against the property, entry route and working space.</>, image: "/large-drilling-rig.webp", alt: "Large borewell drilling machine at an open site", imageTitle: "Large borewell drilling machine for open plots", tag: "Equipment by site", Icon: Cog },
  { title: "Limited-access sites", description: <>Compact equipment may suit some narrow or restricted sites after the route, clearance and working area are assessed.</>, image: "/compact-drilling-rig.webp", alt: "Compact borewell drilling rig in a narrow residential driveway", imageTitle: "Compact borewell drilling for narrow roads in Bengaluru", tag: "Access assessment", Icon: Building2 },
  { title: "Project scope, clearly discussed", description: <>Discuss drilling, casing, pump installation coordination and related work; confirm the applicable scope for your site.</>, image: "/borewell-water-flow.webp", alt: "Water flowing from a completed borewell pipe", imageTitle: "Borewell completion and water flow", tag: "Scope confirmed first", Icon: Wrench },
  { title: "A site-led conversation", description: <>The team can discuss your requirements, site access and next steps based on the conditions at the property.</>, image: "/drilling-team.webp", alt: "Borewell drilling team at a project site", imageTitle: "Borewell drilling team in Bengaluru", tag: "Plan around your site", Icon: UsersRound },
];

const questions = [
  { question: "Can you work on narrow roads?", answer: "That depends on the road width, entry, overhead clearance and space around the drilling point. Share your location and a few site photos so the right approach can be discussed." },
  { question: "Can a survey guarantee water?", answer: "No. A survey can inform planning, but groundwater conditions vary, even between nearby properties. We would never present detection as a guarantee." },
  { question: "What affects the cost of drilling?", answer: "Depth, ground conditions, site access, casing and related work all affect the scope. A useful estimate starts with the particulars of your site." },
  { question: "Where do you work?", answer: "We serve Bengaluru and surrounding areas. Contact us with your locality to confirm availability for your property." },
  { question: "Do you work outside Bengaluru?", answer: "Yes. We discuss borewell sites in every direction around Bengaluru, generally within about 100 km. Tell us your exact location so we can confirm travel and machinery access." },
  { question: "What should I share before a borewell site visit?", answer: "Send your site location, property type, available access width and any existing water or borewell information. Site photos help us discuss suitable drilling machinery and the next step." },
  { question: "Can you help with casing and pump installation?", answer: "We can discuss borewell casing and coordinate pump installation as part of the overall project. The exact scope depends on the site and the completed borewell." },
  { question: "Can an existing borewell be flushed?", answer: "Flushing or redevelopment may help some existing wells, but the condition of the borewell needs to be assessed first. It is not a guarantee of more water." },
];

function Brand({ inverse = false }: { inverse?: boolean }) {
  return <a className={`brand ${inverse ? "brand-inverse" : ""}`} href="#top" aria-label="Eshan Borewells, back to top"><span className="brand-mark"><Droplets size={23} strokeWidth={2.5} /></span><span className="brand-name">ESHAN<span>BOREWELLS</span></span></a>;
}

function ContactLink({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <a className={`button ${className}`} href={contactHref}>{children}<ArrowRight size={18} strokeWidth={2} /></a>;
}

export default function HomePage() {
  const collectionEnabled = Boolean(process.env.LEADS_WEBHOOK_URL);
  const siteUrl = getProductionUrl() || "https://www.eshanborewells.com";
  const localBusiness = buildLocalBusinessSchema(siteUrl, publicBusinessFacts);
  const homePage = buildHomePageSchema(siteUrl, "Eshan Borewells | Borewell Drilling in Bengaluru", publicBusinessFacts.description);
  return <main id="top">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(localBusiness) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(homePage) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: questions.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) }) }} />
    <header id="site-header" className="site-header shell"><Brand /><nav className="desktop-nav" aria-label="Main navigation"><a href="#services">Services</a><a href="#approach">Our approach</a><a href="#why-us">Why us</a><a href="#areas">Where we work</a><a href="#questions">FAQs</a></nav><a className="header-contact" href={contactHref}>Call us<ArrowRight size={16} /></a><MobileMenu /></header>
    <ScrollNav />
    <section className="hero hero-cinematic" aria-labelledby="hero-title"><Image src="/hero-drilling.webp" alt="Borewell drilling rig working at a Bengaluru property" title="Borewell drilling and water solutions in Bengaluru" fill priority sizes="100vw" quality={78} className="hero-background" /><div className="hero-scrim" /><div className="hero-copy shell"><div className="hero-kicker"><span className="kicker-line" /> BOREWELL DRILLING IN BENGALURU</div><h1 id="hero-title">Water starts with <em>the right groundwork.</em></h1><p className="hero-intro">Site-aware drilling and borewell solutions for homes, apartments, farms and businesses across Bengaluru.</p><div className="hero-actions"><a className="button button-primary" href={contactHref}>Discuss your site <ArrowRight size={18} /></a><a className="button button-hero-secondary" href="#services">Explore services <ArrowDownRight size={19} /></a></div><div className="hero-proof" aria-label="Company-reported experience and site count"><div><strong>25+</strong><span>years in the industry</span></div><div><strong>10,000+</strong><span>borewell sites</span></div></div><small className="company-claim-note">Figures reported by Eshan Borewells; not independently verified.</small></div></section>
    <div className="service-ticker" aria-label="Property types we discuss"><div className="shell ticker-inner"><span>HOMES</span><i /> <span>APARTMENTS</span><i /> <span>FARMS</span><i /> <span>COMMERCIAL SITES</span><i /> <span>INDUSTRIAL SITES</span></div></div>
    <section className="services-section section-pad shell" id="services"><div className="section-heading services-heading"><div><span className="section-label">WHAT WE DO</span><h2>Water solutions,<br /><em>considered from the ground up.</em></h2></div><p>Whether you are planning a new borewell or looking after an existing one, the right solution depends on the ground beneath you and the site around you.</p></div><div className="service-list">{services.map((service) => <a className="service-row" key={service.number} href="#contact"><span className="service-number">{service.number}</span><h3>{service.title}</h3><p>{service.description}</p><span className="service-image"><Image src={service.image} alt={service.alt} title={service.imageTitle} fill sizes="(max-width: 540px) 92px, (max-width: 800px) 120px, 170px" quality={76} /></span><ArrowRight size={21} aria-hidden="true" /></a>)}</div><p className="service-footnote">Also need pump installation coordination or other borewell support? <a href="#contact">Tell us what you are working on <ArrowRight size={15} /></a>{phone && <a href={contactHref}>Call now <Phone size={14} /></a>}</p></section>
    <section className="approach-section" id="approach"><div className="shell approach-grid"><div className="approach-intro"><span className="section-label section-label-light">OUR APPROACH</span><h2>The site decides the plan.</h2><p>From tight residential access to open land, we match the conversation and the equipment to the property in front of us.</p><ContactLink className="button-outline">Discuss your site</ContactLink></div><div className="approach-steps"><div><span className="approach-symbol">A</span><h3>Understand the ground</h3><p>We begin with location, access, available space and the water requirement.</p></div><div><span className="approach-symbol">B</span><h3>Choose the right approach</h3><p>Site conditions guide the drilling plan, machinery and scope of work.</p></div><div><span className="approach-symbol">C</span><h3>Complete with clarity</h3><p>Drilling, casing and related work are discussed as one coherent project.</p></div></div></div></section>
    <section className="why-section" id="why-us" aria-labelledby="why-title"><div className="why-banner"><Image src="/why-us-banner.webp" alt="Homeowner checking water beside a borewell drilling rig" title="Bengaluru borewell drilling experience" fill sizes="100vw" quality={76} /><div className="why-banner-shade" /><div className="shell why-banner-content"><span className="section-label">WHY US</span><h2 id="why-title">Borewell experience<br />for <em>25+ years</em></h2><p>Eshan Borewells reports more than 25 years in the industry and work across residential, agricultural and commercial sites. Every site and groundwater condition is different; discuss your requirements before deciding how to proceed.</p><div className="why-metrics"><div><Trophy size={25} /><strong>25+</strong><span>Years in the<br />industry*</span></div><div><Target size={25} /><strong>Site-led</strong><span>Planning around<br />site conditions</span></div><div><UsersRound size={25} /><strong>10,000+</strong><span>Borewell sites<br />(company-reported)*</span></div><div><ShieldCheck size={25} /><strong>Clear scope</strong><span>Requirements<br />discussed first</span></div></div><small className="company-claim-note">*Company-reported figures; project records have not been independently verified.</small></div></div><div className="shell why-cards">{whyCards.map(({ title, description, image, alt, imageTitle, tag, Icon }) => <article className="why-card" key={title}><div className="why-card-photo"><Image src={image} alt={alt} title={imageTitle} fill sizes="(max-width: 540px) 100vw, (max-width: 800px) 45vw, (max-width: 1100px) 30vw, 20vw" quality={76} /></div><div className="why-card-body"><h3>{title}</h3><p>{description}</p><span className="why-card-tag"><Icon size={20} />{tag}</span></div></article>)}</div><div className="why-bottom"><div className="shell why-bottom-inner"><div className="why-benefits"><div><ThumbsUp size={22} /><span><strong>Site conditions first</strong><small>Ground conditions and access vary by site.</small></span></div><div><Leaf size={22} /><span><strong>Access planning</strong><small>Equipment is considered against entry and space.</small></span></div><div><BadgeCheck size={22} /><span><strong>Scope discussed</strong><small>Estimates depend on agreed work and site conditions.</small></span></div><div><Clock3 size={22} /><span><strong>Visit coordination</strong><small>Arrange next steps after confirming site access.</small></span></div><div><Headphones size={22} /><span><strong>After-work enquiries</strong><small>Ask which follow-up services are available.</small></span></div></div><div className="why-bottom-cta"><ContactLink className="button-primary">Call now to discuss a site visit</ContactLink><p><MapPin size={15} /> We serve in and around Bengaluru</p></div></div></div></section>
    <section className="developer-section" aria-labelledby="developers-title"><h2 id="developers-title">Developers we have worked with</h2><div className="developer-marquee" aria-label="Developer clients"><div className="developer-track">{[...verifiedDevelopers, ...verifiedDevelopers].map((developer, index) => <span key={`${developer.name}-${index}`} className="developer-logo" style={{ width: developer.width }} aria-hidden={index >= verifiedDevelopers.length}><span className="developer-logo-image" role="img" aria-label={developer.name} style={{ backgroundPosition: `-${developer.x}px -${developer.y}px`, width: developer.width }} /></span>)}</div></div></section>
    <CustomerReviews reviews={customerReviews} aggregateRating={customerRating} ratingSource={customerRatingSource} feedbackHref={`https://wa.me/${whatsapp || "919844775905"}?text=${encodeURIComponent("Hello Eshan Borewells, I would like to share feedback about my borewell project.")}`} />
    <section className="groundwater-section section-pad shell"><div className="groundwater-rule"><span>BOREWELL SERVICES</span><span>BENGALURU & SURROUNDING AREAS</span></div><div className="groundwater-content"><div className="groundwater-symbol"><Droplets size={49} strokeWidth={1.2} /></div><div><h2>Planning a borewell in Bengaluru?<br /><em>Start with your site.</em></h2><p>Eshan Borewells discusses drilling, groundwater assessment, casing and existing-well flushing for homes, apartments, farms and commercial properties across Bengaluru and nearby areas. Availability, access and groundwater conditions vary by property; share your location to confirm the right next step.</p></div></div></section>
    <section className="areas-section" id="areas"><div className="shell areas-grid"><div><span className="section-label">WHERE WE WORK</span><h2>Borewell services across Bengaluru and nearby areas.</h2></div><div><p>We discuss borewell drilling, groundwater surveys, casing and flushing for homes, apartments, farms and commercial properties in every direction around Bengaluru, generally within about 100 km.</p><div className="area-groups">{areaGroups.map((group) => <div className="area-group" key={group.heading}><h3>{group.heading}</h3><p>{group.areas.join(", ")}</p></div>)}</div><p className="area-note">These are examples of nearby service areas, not a fixed boundary. Share your location so we can confirm availability and site access.</p>{phone && <a className="area-call" href={contactHref}><Phone size={16} /> Call now to discuss your location <ArrowRight size={16} /></a>}</div></div></section>
    <section className="faq-section section-pad shell" id="questions"><div className="faq-intro"><span className="section-label">BEFORE YOU BEGIN</span><h2>Good questions deserve clear answers.</h2></div><div className="faq-list">{questions.map((item, index) => <details key={item.question} className="faq-item"><summary><span className="faq-number">0{index + 1}</span><span>{item.question}</span><span className="faq-toggle" aria-hidden="true">+</span></summary><p>{item.answer}</p></details>)}</div></section>
    <section className="contact-section" id="contact"><div className="shell contact-grid"><div><span className="section-label section-label-light">LET&apos;S START WITH YOUR SITE</span><h2>Tell us where<br />you are drilling.</h2><p>Share your locality, property type and what you need. We can discuss site access, options and the right next step.</p><p className="business-address"><MapPin size={18} />{BUSINESS_ADDRESS}</p></div><div className="contact-card"><span className="contact-card-label">START A CONVERSATION</span>{phone && <a className="contact-option" href={`tel:${phone.replace(/[^+\d]/g, "")}`}><span className="contact-option-icon"><Phone size={20} /></span><span><strong>Call us</strong><small>{phone}</small></span><ArrowRight size={19} /></a>}{whatsappHref && <a className="contact-option" href={whatsappHref} target="_blank" rel="noopener noreferrer"><span className="contact-option-icon"><MessageCircle size={20} /></span><span><strong>Message on WhatsApp</strong><small>+{whatsapp}</small></span><ArrowRight size={19} /></a>}{email && <a className="contact-option" href={`mailto:${email}?subject=Borewell%20site%20enquiry`}><span className="contact-option-icon">@</span><span><strong>Email us</strong><small>{email}</small></span><ArrowRight size={19} /></a>}{!phone && !whatsapp && !email && <div className="contact-unconfigured">Contact details are being added. Please check back shortly for the best way to reach us.</div>}<p className="contact-card-note">For a useful first conversation, have your site location ready.</p></div></div></section>
    <footer className="site-footer"><div className="shell footer-top"><div className="footer-brand"><Brand inverse /><p>Borewell drilling and water solutions for properties across Bengaluru.</p></div></div><div className="shell footer-lead"><div><span className="section-label section-label-light">TELL US ABOUT YOUR SITE</span><h2>{collectionEnabled ? "Get a call about your borewell." : "Start your borewell enquiry."}</h2><p>{collectionEnabled ? "Leave your name, phone number and site location. We will use them only to follow up on your enquiry." : "Enter your details, then send them to us in WhatsApp to start a conversation."}</p></div><LeadForm source="footer" whatsapp={whatsapp} phone={phone} collectionEnabled={collectionEnabled} /></div><div className="shell footer-info"><nav className="footer-details footer-service-links" aria-labelledby="footer-services-title"><h3 id="footer-services-title">Explore services and local guidance</h3><ul>{indexableSeoPages.map((page) => <li key={page.slug}><Link href={`/${page.slug}`}>{page.title}<ArrowRight size={14} /></Link></li>)}</ul></nav><div className="footer-details"><h3>Our office</h3><address><MapPin size={18} />{BUSINESS_ADDRESS}</address></div><div className="footer-details"><h3>Speak with us</h3>{phone && <a href={`tel:${phone.replace(/[^+\d]/g, "")}`}><Phone size={18} />{phone}</a>}{whatsappHref && <a href={whatsappHref} target="_blank" rel="noopener noreferrer"><MessageCircle size={18} />Chat on WhatsApp</a>}</div></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} Eshan Borewells</span><a href="#top">Back to top ↑</a></div></footer>
    <EnquiryPopup whatsapp={whatsapp} phone={phone} collectionEnabled={collectionEnabled} />
    {phone && <a className="floating-call" href={contactHref}><Phone size={17} />Call now</a>}
  </main>;
}
