import Image from "next/image";
import { ArrowDownRight, ArrowRight, BadgeCheck, Building2, Clock3, Cog, Droplets, Headphones, Leaf, MapPin, MessageCircle, Phone, ShieldCheck, Target, ThumbsUp, Trophy, UsersRound, Wrench } from "lucide-react";
import { BUSINESS_ADDRESS, BUSINESS_EMAIL, BUSINESS_PHONE, WHATSAPP_NUMBER } from "./business-config";
import { MobileMenu } from "./mobile-menu";
import { EnquiryPopup } from "./enquiry-popup";
import { verifiedDevelopers } from "./verified-projects";
import { ScrollNav } from "./scroll-nav";

const phone = /^\+?[\d\s()-]{8,}$/.test(BUSINESS_PHONE) ? BUSINESS_PHONE : null;
const whatsapp = /^\d{10,15}$/.test(WHATSAPP_NUMBER.replace(/\D/g, "")) ? WHATSAPP_NUMBER.replace(/\D/g, "") : null;
const email = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(BUSINESS_EMAIL) ? BUSINESS_EMAIL : null;
const contactHref = phone ? `tel:${phone.replace(/[^+\d]/g, "")}` : "#contact";
const whatsappHref = whatsapp ? `https://wa.me/${whatsapp}?text=${encodeURIComponent("Hello Eshan Borewells, I would like to discuss a borewell site visit. My location is: ")}` : null;

const services = [
  { number: "01", title: "Borewell drilling", description: "Drilling planned around your site, access and property requirements.", image: "/large-drilling-rig.jpg", alt: "Illustrative photograph of a large borewell drilling rig on open land" },
  { number: "02", title: "Water detection & survey", description: "A grounded assessment to help decide where and how to proceed.", image: "/survey-technician.jpg", alt: "Illustrative photograph of a technician reviewing a site survey" },
  { number: "03", title: "Casing & completion", description: "The supporting work needed to protect and complete a new borewell.", image: "/casing-installation.jpg", alt: "Illustrative photograph of borewell casing being installed" },
  { number: "04", title: "Flushing & redevelopment", description: "Care for suitable existing wells, assessed against their condition.", image: "/borewell-water-flow.jpg", alt: "Illustrative photograph of water flowing from a borewell pipe" },
];

const whyCards = [
  { title: "Advanced Water Detection Technology", description: <>We use scientific methods and modern survey equipment to identify water presence with <strong>99% accuracy</strong> before drilling.</>, image: "/survey-technician.jpg", alt: "Illustrative photograph of a technician using survey equipment", tag: "Drill with Confidence", Icon: Target },
  { title: "Range of Drilling Machines", description: <>From large high-capacity rigs for open plots and agricultural land to compact machines and <strong>robo vehicles</strong> for houses, apartments and narrow roads, we have the right solution for every site.</>, image: "/large-drilling-rig.jpg", alt: "Illustrative photograph of a large drilling machine", tag: "Any Site, Any Challenge", Icon: Cog },
  { title: "Narrow Roads? No Worries!", description: <>We have compact drilling machines and robotic vehicles designed to work in tight spaces, narrow roads and inside existing buildings without damage.</>, image: "/compact-drilling-rig.jpg", alt: "Illustrative photograph of a compact rig in a narrow apartment driveway", tag: "Solutions for Limited Space", Icon: Building2 },
  { title: "Complete Turnkey Solutions", description: <>We handle everything: site survey, drilling, casing, pump installation, electrical and handover. You get a complete borewell solution without any hassle.</>, image: "/borewell-water-flow.jpg", alt: "Illustrative photograph of water flowing from a completed borewell", tag: "End-to-End Service", Icon: Wrench },
  { title: "Experienced & Skilled Team", description: <>Our trained professionals ensure safe, efficient and high-quality drilling with proper safety standards and minimal disturbance to your property.</>, image: "/drilling-team.jpg", alt: "Illustrative photograph representing a skilled borewell team", tag: "Trained & Reliable Team", Icon: UsersRound },
];

const questions = [
  { question: "Can you work on narrow roads?", answer: "That depends on the road width, entry, overhead clearance and space around the drilling point. Share your location and a few site photos so the right approach can be discussed." },
  { question: "Can a survey guarantee water?", answer: "No. A survey can inform planning, but groundwater conditions vary, even between nearby properties. We would never present detection as a guarantee." },
  { question: "What affects the cost of drilling?", answer: "Depth, ground conditions, site access, casing and related work all affect the scope. A useful estimate starts with the particulars of your site." },
  { question: "Where do you work?", answer: "We serve Bengaluru and surrounding areas. Contact us with your locality to confirm availability for your property." },
];

function Brand({ inverse = false }: { inverse?: boolean }) {
  return <a className={`brand ${inverse ? "brand-inverse" : ""}`} href="#top" aria-label="Eshan Borewells, back to top"><span className="brand-mark"><Droplets size={23} strokeWidth={2.5} /></span><span className="brand-name">ESHAN<span>BOREWELLS</span></span></a>;
}

function ContactLink({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <a className={`button ${className}`} href={contactHref}>{children}<ArrowRight size={18} strokeWidth={2} /></a>;
}

export default function HomePage() {
  const localBusiness = { "@context": "https://schema.org", "@type": "LocalBusiness", name: "Eshan Borewells", description: "Borewell drilling and water solutions in Bengaluru and surrounding areas.", areaServed: "Bengaluru", address: { "@type": "PostalAddress", streetAddress: "6th Block, Rajajinagar", addressLocality: "Bengaluru", addressRegion: "Karnataka", addressCountry: "IN" }, ...(phone ? { telephone: phone } : {}), ...(email ? { email } : {}) };
  return <main id="top">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(localBusiness) }} />
    <header id="site-header" className="site-header shell"><Brand /><nav className="desktop-nav" aria-label="Main navigation"><a href="#services">Services</a><a href="#approach">Our approach</a><a href="#why-us">Why us</a><a href="#areas">Where we work</a><a href="#questions">FAQs</a></nav><a className="header-contact" href={contactHref}>Call us<ArrowRight size={16} /></a><MobileMenu /></header>
    <ScrollNav />
    <section className="hero hero-cinematic" aria-labelledby="hero-title"><Image src="/hero-drilling.png" alt="Illustrative image of a borewell drilling rig at work" fill priority sizes="100vw" className="hero-background" /><div className="hero-scrim" /><div className="hero-copy shell"><div className="hero-kicker"><span className="kicker-line" /> BOREWELL DRILLING IN BENGALURU</div><h1 id="hero-title">Water starts with <em>the right groundwork.</em></h1><p className="hero-intro">Site-aware drilling and borewell solutions for homes, apartments, farms and businesses across Bengaluru.</p><div className="hero-actions"><ContactLink className="button-primary">Discuss your site</ContactLink><a className="button button-hero-secondary" href="#services">Explore services <ArrowDownRight size={19} /></a></div><div className="hero-proof" aria-label="Our experience"><div><strong>25+</strong><span>years in the industry</span></div><div><strong>10,000+</strong><span>borewell sites</span></div></div></div></section>
    <div className="service-ticker" aria-label="Property types we discuss"><div className="shell ticker-inner"><span>HOMES</span><i /> <span>APARTMENTS</span><i /> <span>FARMS</span><i /> <span>COMMERCIAL SITES</span><i /> <span>INDUSTRIAL SITES</span></div></div>
    <section className="services-section section-pad shell" id="services"><div className="section-heading services-heading"><div><span className="section-label">WHAT WE DO</span><h2>Water solutions,<br /><em>considered from the ground up.</em></h2></div><p>Whether you are planning a new borewell or looking after an existing one, the right solution depends on the ground beneath you and the site around you.</p></div><div className="service-list">{services.map((service) => <a className="service-row" key={service.number} href="#contact"><span className="service-number">{service.number}</span><h3>{service.title}</h3><p>{service.description}</p><span className="service-image"><Image src={service.image} alt={service.alt} fill sizes="(max-width: 800px) 100vw, 180px" /></span><ArrowRight size={21} aria-hidden="true" /></a>)}</div><p className="service-footnote">Also need pump installation coordination or other borewell support? <a href="#contact">Tell us what you are working on <ArrowRight size={15} /></a></p></section>
    <section className="approach-section" id="approach"><div className="shell approach-grid"><div className="approach-intro"><span className="section-label section-label-light">OUR APPROACH</span><h2>The site decides the plan.</h2><p>From tight residential access to open land, we match the conversation and the equipment to the property in front of us.</p><ContactLink className="button-outline">Discuss your site</ContactLink></div><div className="approach-steps"><div><span className="approach-symbol">A</span><h3>Understand the ground</h3><p>We begin with location, access, available space and the water requirement.</p></div><div><span className="approach-symbol">B</span><h3>Choose the right approach</h3><p>Site conditions guide the drilling plan, machinery and scope of work.</p></div><div><span className="approach-symbol">C</span><h3>Complete with clarity</h3><p>Drilling, casing and related work are discussed as one coherent project.</p></div></div></div></section>
    <section className="why-section" id="why-us" aria-labelledby="why-title"><div className="why-banner"><Image src="/why-us-banner.jpg" alt="Illustrative photograph of a homeowner checking water beside a borewell rig" fill sizes="100vw" /><div className="why-banner-shade" /><div className="shell why-banner-content"><span className="section-label">WHY US</span><h2 id="why-title">Trusted Borewell Experts<br />for <em>25+ Years</em></h2><p>For over 25 years, we have been helping homeowners, farmers and businesses find reliable water sources with high success and complete peace of mind.</p><div className="why-metrics"><div><Trophy size={25} /><strong>25+</strong><span>Years of<br />Experience</span></div><div><Target size={25} /><strong>99%</strong><span>Accurate Water<br />Presence Detection</span></div><div><UsersRound size={25} /><strong>10,000+</strong><span>Successful<br />Borewell Projects</span></div><div><ShieldCheck size={25} /><strong>100%</strong><span>Customer<br />Satisfaction</span></div></div></div></div><div className="shell why-cards">{whyCards.map(({ title, description, image, alt, tag, Icon }) => <article className="why-card" key={title}><div className="why-card-photo"><Image src={image} alt={alt} fill sizes="(max-width: 800px) 80vw, 20vw" /></div><div className="why-card-body"><h3>{title}</h3><p>{description}</p><span className="why-card-tag"><Icon size={20} />{tag}</span></div></article>)}</div><div className="why-bottom"><div className="shell why-bottom-inner"><div className="why-benefits"><div><ThumbsUp size={22} /><span><strong>High Success Rate</strong><small>99% accurate water presence detection.</small></span></div><div><Leaf size={22} /><span><strong>Minimal Property Damage</strong><small>Advanced machines for safe and clean operation.</small></span></div><div><BadgeCheck size={22} /><span><strong>Transparent Pricing</strong><small>No hidden costs. Clear estimates.</small></span></div><div><Clock3 size={22} /><span><strong>On-Time Completion</strong><small>We value your time and deliver as promised.</small></span></div><div><Headphones size={22} /><span><strong>Ongoing Support</strong><small>Maintenance and support even after the job.</small></span></div></div><div className="why-bottom-cta"><ContactLink className="button-primary">Call now for a free site visit</ContactLink><p><MapPin size={15} /> We serve in and around Bengaluru</p></div></div></div></section>
    <section className="developer-section" aria-labelledby="developers-title"><h2 id="developers-title">Developers we have worked with</h2><div className="developer-marquee" aria-label="Developer clients"><div className="developer-track">{[...verifiedDevelopers, ...verifiedDevelopers].map((developer, index) => <span key={`${developer.name}-${index}`} className="developer-logo" style={{ width: developer.width }} aria-hidden={index >= verifiedDevelopers.length}><span className="developer-logo-image" role="img" aria-label={developer.name} style={{ backgroundPosition: `-${developer.x}px -${developer.y}px`, width: developer.width }} /></span>)}</div></div></section>
    <section className="groundwater-section section-pad shell"><div className="groundwater-rule"><span>THE HONEST VIEW</span><span>WATER DETECTION</span></div><div className="groundwater-content"><div className="groundwater-symbol"><Droplets size={49} strokeWidth={1.2} /></div><div><h2>A survey can guide a decision.<br /><em>It cannot promise water.</em></h2><p>Groundwater is never a certainty. You deserve a candid conversation about assessment, site conditions and what remains unknown before drilling begins.</p></div></div></section>
    <section className="areas-section" id="areas"><div className="shell areas-grid"><div><span className="section-label">WHERE WE WORK</span><h2>Local to Bengaluru.<br />Focused on your site.</h2></div><div><p>From individual homes and apartment properties to farms and larger sites, we discuss borewell requirements across Bengaluru and nearby areas.</p><div className="area-pills"><span>North Bengaluru</span><span>South Bengaluru</span><span>East Bengaluru</span><span>West Bengaluru</span><span>Surrounding areas</span></div><p className="area-note">Availability is confirmed based on your exact locality and site access.</p></div></div></section>
    <section className="faq-section section-pad shell" id="questions"><div className="faq-intro"><span className="section-label">BEFORE YOU BEGIN</span><h2>Good questions deserve clear answers.</h2></div><div className="faq-list">{questions.map((item, index) => <details key={item.question} className="faq-item"><summary><span className="faq-number">0{index + 1}</span><span>{item.question}</span><span className="faq-toggle" aria-hidden="true">+</span></summary><p>{item.answer}</p></details>)}</div></section>
    <section className="contact-section" id="contact"><div className="shell contact-grid"><div><span className="section-label section-label-light">LET&apos;S START WITH YOUR SITE</span><h2>Tell us where<br />you are drilling.</h2><p>Share your locality, property type and what you need. We can discuss site access, options and the right next step.</p><p className="business-address"><MapPin size={18} />{BUSINESS_ADDRESS}</p></div><div className="contact-card"><span className="contact-card-label">START A CONVERSATION</span>{phone && <a className="contact-option" href={`tel:${phone.replace(/[^+\d]/g, "")}`}><span className="contact-option-icon"><Phone size={20} /></span><span><strong>Call us</strong><small>{phone}</small></span><ArrowRight size={19} /></a>}{whatsappHref && <a className="contact-option" href={whatsappHref} target="_blank" rel="noopener noreferrer"><span className="contact-option-icon"><MessageCircle size={20} /></span><span><strong>Message on WhatsApp</strong><small>+{whatsapp}</small></span><ArrowRight size={19} /></a>}{email && <a className="contact-option" href={`mailto:${email}?subject=Borewell%20site%20enquiry`}><span className="contact-option-icon">@</span><span><strong>Email us</strong><small>{email}</small></span><ArrowRight size={19} /></a>}{!phone && !whatsapp && !email && <div className="contact-unconfigured">Contact details are being added. Please check back shortly for the best way to reach us.</div>}<p className="contact-card-note">For a useful first conversation, have your site location ready.</p></div></div></section>
    <footer className="site-footer"><div className="shell footer-top"><div className="footer-brand"><Brand inverse /><p>Borewell drilling and water solutions for properties across Bengaluru.</p></div><div className="footer-details"><h3>Our office</h3><address><MapPin size={18} />{BUSINESS_ADDRESS}</address></div><div className="footer-details"><h3>Speak with us</h3>{phone && <a href={`tel:${phone.replace(/[^+\d]/g, "")}`}><Phone size={18} />{phone}</a>}{whatsappHref && <a href={whatsappHref} target="_blank" rel="noopener noreferrer"><MessageCircle size={18} />Chat on WhatsApp</a>}</div></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} Eshan Borewells</span><a href="#top">Back to top ↑</a></div></footer>
    <EnquiryPopup whatsapp={whatsapp} email={email} />
  </main>;
}
