import Image from "next/image";
import { ArrowDownRight, ArrowRight, Droplets, MapPin, MessageCircle, Phone } from "lucide-react";
import { BUSINESS_EMAIL, BUSINESS_PHONE, WHATSAPP_NUMBER } from "./business-config";
import { MobileMenu } from "./mobile-menu";

const phone = /^\+?[\d\s()-]{8,}$/.test(BUSINESS_PHONE) ? BUSINESS_PHONE : null;
const whatsapp = /^\d{10,15}$/.test(WHATSAPP_NUMBER.replace(/\D/g, "")) ? WHATSAPP_NUMBER.replace(/\D/g, "") : null;
const email = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(BUSINESS_EMAIL) ? BUSINESS_EMAIL : null;
const contactHref = phone ? `tel:${phone.replace(/[^+\d]/g, "")}` : "#contact";
const whatsappHref = whatsapp ? `https://wa.me/${whatsapp}?text=${encodeURIComponent("Hello Eshan Borewells, I would like to discuss a borewell site visit. My location is: ")}` : null;

const services = [
  { number: "01", title: "Borewell drilling", description: "Drilling planned around your site, access and property requirements." },
  { number: "02", title: "Water detection & survey", description: "A grounded assessment to help decide where and how to proceed." },
  { number: "03", title: "Casing & completion", description: "The supporting work needed to protect and complete a new borewell." },
  { number: "04", title: "Flushing & redevelopment", description: "Care for suitable existing wells, assessed against their condition." },
];

const questions = [
  { question: "Can you work on narrow roads?", answer: "That depends on the road width, entry, overhead clearance and space around the drilling point. Share your location and a few site photos so the right approach can be discussed." },
  { question: "Can a survey guarantee water?", answer: "No. A survey can inform planning, but groundwater conditions vary, even between nearby properties. We would never present detection as a guarantee." },
  { question: "What affects the cost of drilling?", answer: "Depth, ground conditions, site access, casing and related work all affect the scope. A useful estimate starts with the particulars of your site." },
  { question: "Where do you work?", answer: "We serve Bengaluru and surrounding areas. Contact us with your locality to confirm availability for your property." },
];

function Brand({ inverse = false }: { inverse?: boolean }) {
  return <a className={`brand ${inverse ? "brand-inverse" : ""}`} href="#top" aria-label="Eshan Borewells, back to top"><span className="brand-mark"><Droplets size={23} strokeWidth={2.5} /></span><span className="brand-name">ESHAN<span>BOREWELLS</span></span></a>;
}

function ContactLink({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <a className={`button ${className}`} href={contactHref}>{children}<ArrowRight size={18} strokeWidth={2} /></a>;
}

export default function HomePage() {
  const localBusiness = { "@context": "https://schema.org", "@type": "LocalBusiness", name: "Eshan Borewells", description: "Borewell drilling and water solutions in Bengaluru and surrounding areas.", areaServed: "Bengaluru", ...(phone ? { telephone: phone } : {}), ...(email ? { email } : {}) };
  return <main id="top">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(localBusiness) }} />
    <div className="announcement"><span className="announcement-dot" /> Borewell services in Bengaluru & nearby areas</div>
    <header className="site-header shell"><Brand /><nav className="desktop-nav" aria-label="Main navigation"><a href="#services">Services</a><a href="#approach">Our approach</a><a href="#areas">Where we work</a><a href="#questions">FAQs</a></nav><a className="header-contact" href={contactHref}>{phone ? "Call us" : "Get in touch"}<ArrowRight size={16} /></a><MobileMenu /></header>
    <section className="hero shell" aria-labelledby="hero-title"><div className="hero-copy"><div className="hero-kicker"><span className="kicker-line" /> BUILT FOR BENGALURU SITES</div><h1 id="hero-title">A better way to <em>begin</em> a borewell.</h1><p className="hero-intro">From the first site conversation to drilling and completion, Eshan Borewells helps you make informed decisions about water for your property.</p><div className="hero-actions"><ContactLink className="button-primary">Discuss your site</ContactLink><a className="text-link" href="#services">Explore services <ArrowDownRight size={19} /></a></div><div className="hero-note"><MapPin size={18} /> Serving Bengaluru and surrounding areas</div></div><div className="hero-visual"><Image src="/hero-drilling.png" alt="Illustrative image of a borewell drilling rig at work" fill priority sizes="(max-width: 900px) 100vw, 55vw" className="hero-image" /><span className="image-index">01 / THE WORK</span><div className="image-caption">Every good borewell starts with a good question: <strong>what does this site need?</strong></div></div></section>
    <div className="service-ticker" aria-label="Property types we discuss"><div className="shell ticker-inner"><span>HOMES</span><i /> <span>APARTMENTS</span><i /> <span>FARMS</span><i /> <span>COMMERCIAL SITES</span><i /> <span>INDUSTRIAL SITES</span></div></div>
    <section className="services-section section-pad shell" id="services"><div className="section-heading services-heading"><div><span className="section-label">WHAT WE DO</span><h2>Water solutions,<br /><em>considered from the ground up.</em></h2></div><p>Whether you are planning a new borewell or looking after an existing one, the right solution depends on the ground beneath you and the site around you.</p></div><div className="service-list">{services.map((service) => <a className="service-row" key={service.number} href="#contact"><span className="service-number">{service.number}</span><h3>{service.title}</h3><p>{service.description}</p><ArrowRight size={21} aria-hidden="true" /></a>)}</div><p className="service-footnote">Also need pump installation coordination or other borewell support? <a href="#contact">Tell us what you are working on <ArrowRight size={15} /></a></p></section>
    <section className="approach-section" id="approach"><div className="shell approach-grid"><div className="approach-intro"><span className="section-label section-label-light">OUR APPROACH</span><h2>Not every site calls for the same machine.</h2><p>A plot, a narrow street and a working commercial property each bring different constraints. We start by understanding the site, then discuss a practical way forward.</p><ContactLink className="button-outline">Talk through your site</ContactLink></div><div className="approach-steps"><div><span>01 / UNDERSTAND</span><h3>Tell us about the property.</h3><p>Location, access, available space and the water requirement all matter.</p></div><div><span>02 / ASSESS</span><h3>Plan around real conditions.</h3><p>A site discussion helps identify suitable equipment and the scope of work.</p></div><div><span>03 / PROCEED</span><h3>Know the next steps.</h3><p>Get a clearer picture of drilling, casing and related completion needs.</p></div></div></div></section>
    <section className="groundwater-section section-pad shell"><div className="groundwater-rule"><span>THE HONEST VIEW</span><span>WATER DETECTION</span></div><div className="groundwater-content"><div className="groundwater-symbol"><Droplets size={49} strokeWidth={1.2} /></div><div><h2>A survey can guide a decision.<br /><em>It cannot promise water.</em></h2><p>Groundwater is never a certainty. You deserve a candid conversation about assessment, site conditions and what remains unknown before drilling begins.</p></div></div></section>
    <section className="areas-section" id="areas"><div className="shell areas-grid"><div><span className="section-label">WHERE WE WORK</span><h2>Local to Bengaluru.<br />Focused on your site.</h2></div><div><p>From individual homes and apartment properties to farms and larger sites, we discuss borewell requirements across Bengaluru and nearby areas.</p><div className="area-pills"><span>North Bengaluru</span><span>South Bengaluru</span><span>East Bengaluru</span><span>West Bengaluru</span><span>Surrounding areas</span></div><p className="area-note">Availability is confirmed based on your exact locality and site access.</p></div></div></section>
    <section className="faq-section section-pad shell" id="questions"><div className="faq-intro"><span className="section-label">BEFORE YOU BEGIN</span><h2>Good questions deserve clear answers.</h2></div><div className="faq-list">{questions.map((item, index) => <details key={item.question} className="faq-item"><summary><span className="faq-number">0{index + 1}</span><span>{item.question}</span><span className="faq-toggle" aria-hidden="true">+</span></summary><p>{item.answer}</p></details>)}</div></section>
    <section className="contact-section" id="contact"><div className="shell contact-grid"><div><span className="section-label section-label-light">LET&apos;S START WITH YOUR SITE</span><h2>Tell us where<br />you are drilling.</h2><p>Share your locality, property type and what you need. We can discuss site access, options and the right next step.</p></div><div className="contact-card"><span className="contact-card-label">START A CONVERSATION</span>{phone && <a className="contact-option" href={`tel:${phone.replace(/[^+\d]/g, "")}`}><span className="contact-option-icon"><Phone size={20} /></span><span><strong>Call us</strong><small>{phone}</small></span><ArrowRight size={19} /></a>}{whatsappHref && <a className="contact-option" href={whatsappHref} target="_blank" rel="noopener noreferrer"><span className="contact-option-icon"><MessageCircle size={20} /></span><span><strong>Message on WhatsApp</strong><small>Share your site details</small></span><ArrowRight size={19} /></a>}{email && <a className="contact-option" href={`mailto:${email}?subject=Borewell%20site%20enquiry`}><span className="contact-option-icon">@</span><span><strong>Email us</strong><small>{email}</small></span><ArrowRight size={19} /></a>}{!phone && !whatsapp && !email && <div className="contact-unconfigured">Contact details are being added. Please check back shortly for the best way to reach us.</div>}<p className="contact-card-note">For a useful first conversation, have your area and property type ready.</p></div></div></section>
    <footer className="site-footer"><div className="shell footer-top"><Brand inverse /><p>Borewell drilling and water solutions in Bengaluru and surrounding areas.</p><a href="#top">Back to top ↑</a></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} Eshan Borewells</span><span>Built on clear conversations and practical work.</span></div></footer>
  </main>;
}
